export const MobilityAuditEvents = {
 CREATE_LOCATION: 'CREATE_LOCATION',
 CREATE_TRIP: 'CREATE_TRIP',
 REQUEST_ASSISTANCE: 'REQUEST_ASSISTANCE',
 ASSIGN_DRIVER: 'ASSIGN_DRIVER',
 COMPLETE_TRIP: 'COMPLETE_TRIP'
};
